// 3D cosmetics that exist in the LEGO client (lego-client/src/main/java/dev/lego/cosmetic).
// Generated from the client's registration calls (Cos.add / Cos.cape); the ids
// must stay identical to the client's ids. Names are the client's German names.
// Regenerate with: node tools/extract-cosmetics.mjs (see docs/ANALYSIS.md).

export const COSMETIC_SLOTS = ['cape', 'wings', 'hat', 'face', 'back', 'aura', 'pet', 'vehicle'] as const;
export type CosmeticSlot = (typeof COSMETIC_SLOTS)[number];

export type ClientCosmeticSeed = [id: string, name: string, slot: CosmeticSlot, rarity: 'common' | 'rare' | 'epic' | 'legendary'];

export const CLIENT_COSMETICS: readonly ClientCosmeticSeed[] = [
  ['aura_fire', 'Feuer-Aura', 'aura', 'legendary'],
  ['aura_frost', 'Frost-Aura', 'aura', 'epic'],
  ['aura_hearts', 'Herz-Aura', 'aura', 'rare'],
  ['aura_orbit', 'Sternen-Orbit', 'aura', 'legendary'],
  ['aura_storm', 'Gewitter-Aura', 'aura', 'legendary'],
  ['aura_sakura', 'Kirschblüten-Wind', 'aura', 'epic'],
  ['aura_music', 'Musik-Aura', 'aura', 'rare'],
  ['aura_bubbles', 'Seifenblasen', 'aura', 'common'],
  ['aura_rainbow', 'Regenbogen-Ring', 'aura', 'epic'],
  ['aura_void', 'Leere-Aura', 'aura', 'legendary'],
  ['aura_sparkle', 'Glitzerstaub', 'aura', 'rare'],
  ['aura_leaves', 'Herbstlaub', 'aura', 'common'],
  ['aura_runes', 'Runenkreis', 'aura', 'legendary'],
  ['aura_bricks', 'Stein-Orbit', 'aura', 'epic'],
  ['aura_c3_splash', 'Wasser-Splash', 'aura', 'epic'],
  ['aura_c3_book', 'Zauberbuch-Orbit', 'aura', 'legendary'],
  ['aura_c3_hexshield', 'Hex-Schild', 'aura', 'epic'],
  ['aura_c3_tesla', 'Tesla-Feld', 'aura', 'legendary'],
  ['aura_c3_planets', 'Mini-Sonnensystem', 'aura', 'legendary'],
  ['wings_c3_mech', 'Mecha-Schwingen', 'wings', 'legendary'],
  ['wings_c3_prism', 'Prismenflügel', 'wings', 'epic'],
  ['back_c3_minime', 'MiniMe-Anhänger', 'back', 'legendary'],
  ['back_c3_minime_chain', 'MiniMe-Kette', 'back', 'legendary'],
  ['back_c3_foxtail', 'Fuchsschwanz', 'back', 'epic'],
  ['back_c3_dragontail', 'Drachenschwanz', 'back', 'legendary'],
  ['back_c3_parrot', 'Schulterpapagei', 'back', 'epic'],
  ['back_c3_shoulderdragon', 'Schulterdrache', 'back', 'legendary'],
  ['back_c3_katana', 'Katana', 'back', 'epic'],
  ['back_c3_jetpack2', 'Jetpack V2', 'back', 'legendary'],
  ['back_c3_lantern', 'Gürtellaterne', 'back', 'rare'],
  ['hat_c3_crystalcrown', 'Schwebende Kristallkrone', 'hat', 'legendary'],
  ['hat_c3_planetring', 'Planetenring', 'hat', 'legendary'],
  ['hat_c3_rayhalo', 'Strahlenkranz', 'hat', 'epic'],
  ['hat_c3_flamecrown', 'Flammenkrone', 'hat', 'legendary'],
  ['hat_c3_bubble', 'Blasenhelm', 'hat', 'epic'],
  ['hat_c3_catphones', 'Katzen-Kopfhörer', 'hat', 'epic'],
  ['hat_c3_snowglobe', 'Schneekugel', 'hat', 'epic'],
  ['hat_c3_pumpkin', 'Kürbiskopf', 'hat', 'epic'],
  ['hat_c3_band_bolt', 'Blitz-Bandana', 'hat', 'rare'],
  ['hat_c3_band_fire', 'Flammen-Bandana', 'hat', 'rare'],
  ['hat_c3_band_ice', 'Frost-Stirnband', 'hat', 'rare'],
  ['face_c3_holovisor', 'Holo-Visier', 'face', 'legendary'],
  ['face_c3_neonshades', 'Neon-Shades', 'face', 'epic'],
  ['cape_c3void', 'Leerenmantel', 'cape', 'legendary'],
  ['cape_c3nether', 'Netherglut', 'cape', 'epic'],
  ['cape_c3heaven', 'Himmelsgold', 'cape', 'legendary'],
  ['cape_c3sunflower', 'Sonnenblume', 'cape', 'rare'],
  ['cape_c3pumpkin', 'Kürbislaterne', 'cape', 'epic'],
  ['cape_c3ghost', 'Geisterchen', 'cape', 'epic'],
  ['cape_c3skull', 'Leuchtschädel', 'cape', 'epic'],
  ['cape_c3bolt_purple', 'Neonblitz Lila', 'cape', 'epic'],
  ['cape_c3bolt_blue', 'Neonblitz Blau', 'cape', 'epic'],
  ['cape_c3bolt_green', 'Neonblitz Grün', 'cape', 'epic'],
  ['cape_c3bolt_orange', 'Neonblitz Orange', 'cape', 'epic'],
  ['cape_c3embertree', 'Glutbaum', 'cape', 'legendary'],
  ['hat_crown', 'Königskrone', 'hat', 'legendary'],
  ['hat_halo', 'Heiligenschein', 'hat', 'epic'],
  ['hat_tophat', 'Zylinder', 'hat', 'rare'],
  ['hat_santa', 'Weihnachtsmütze', 'hat', 'rare'],
  ['hat_witch', 'Hexenhut', 'hat', 'epic'],
  ['hat_cat', 'Katzenohren', 'hat', 'common'],
  ['hat_bunny', 'Hasenohren', 'hat', 'common'],
  ['hat_horns', 'Teufelshörner', 'hat', 'epic'],
  ['hat_headphones', 'Kopfhörer', 'hat', 'rare'],
  ['face_sunglasses', 'Sonnenbrille', 'face', 'rare'],
  ['face_pixel', 'Pixel-Brille', 'face', 'common'],
  ['back_lego', 'Lego-Rucksack', 'back', 'epic'],
  ['back_sword', 'Kristallschwert', 'back', 'rare'],
  ['cape_lego', 'Lego-Umhang', 'cape', 'rare'],
  ['cape_galaxy', 'Galaxie', 'cape', 'epic'],
  ['cape_flames', 'Flammen', 'cape', 'rare'],
  ['cape_ice', 'Eiskristall', 'cape', 'rare'],
  ['cape_aurora', 'Polarlicht', 'cape', 'epic'],
  ['cape_sunset', 'Retro-Sonnenuntergang', 'cape', 'rare'],
  ['cape_carbon', 'Carbon', 'cape', 'common'],
  ['cape_neon', 'Neon-Grid', 'cape', 'epic'],
  ['cape_spotify', 'Spotify', 'cape', 'legendary'],
  ['cape_sakura', 'Kirschblüte', 'cape', 'epic'],
  ['cape_lava', 'Lavastrom', 'cape', 'epic'],
  ['cape_ocean', 'Tiefsee', 'cape', 'rare'],
  ['cape_matrix', 'Matrix-Code', 'cape', 'epic'],
  ['cape_storm', 'Gewitter', 'cape', 'epic'],
  ['cape_rainbow', 'Regenbogen-Seide', 'cape', 'rare'],
  ['cape_snow', 'Winternacht', 'cape', 'rare'],
  ['cape_fireflies', 'Glühwürmchen', 'cape', 'epic'],
  ['cape_heart', 'Herzschlag', 'cape', 'rare'],
  ['cape_enchant', 'Verzaubert', 'cape', 'legendary'],
  ['cape_void', 'Schwarzes Loch', 'cape', 'legendary'],
  ['cape_royal', 'Königsmantel', 'cape', 'legendary'],
  ['cape_dragon', 'Drachenschuppen', 'cape', 'epic'],
  ['cape_camo', 'Tarnmuster', 'cape', 'common'],
  ['cape_bricks', 'Bausteine', 'cape', 'common'],
  ['cape_racing', 'Zielflagge', 'cape', 'common'],
  ['cape_moon', 'Mondnacht', 'cape', 'rare'],
  ['hat_fox', 'Fuchsohren', 'hat', 'common'],
  ['hat_cowboy', 'Cowboyhut', 'hat', 'rare'],
  ['hat_beanie', 'Bommelmütze', 'hat', 'common'],
  ['hat_flowers', 'Blumenkranz', 'hat', 'rare'],
  ['hat_viking', 'Wikingerhelm', 'hat', 'epic'],
  ['hat_propeller', 'Propellermütze', 'hat', 'rare'],
  ['hat_chef', 'Kochmütze', 'hat', 'common'],
  ['hat_party', 'Partyhut', 'hat', 'common'],
  ['hat_wizard', 'Zaubererhut', 'hat', 'legendary'],
  ['hat_alien', 'Alien-Antennen', 'hat', 'rare'],
  ['hat_bow', 'Große Schleife', 'hat', 'common'],
  ['hat_mushroom', 'Pilzhut', 'hat', 'epic'],
  ['face_hearts', 'Herzbrille', 'face', 'rare'],
  ['face_stars', 'Sternenbrille', 'face', 'rare'],
  ['face_monocle', 'Monokel', 'face', 'epic'],
  ['face_mustache', 'Schnurrbart', 'face', 'common'],
  ['face_clown', 'Clownsnase', 'face', 'common'],
  ['face_visor', 'Cyber-Visier', 'face', 'legendary'],
  ['face_masq', 'Maskenball', 'face', 'epic'],
  ['face_ninja', 'Ninja-Maske', 'face', 'rare'],
  ['back_guitar', 'E-Gitarre', 'back', 'epic'],
  ['back_jetpack', 'Jetpack', 'back', 'legendary'],
  ['back_shield', 'Ritterschild', 'back', 'rare'],
  ['back_quiver', 'Köcher', 'back', 'rare'],
  ['back_rocket', 'Rakete', 'back', 'epic'],
  ['back_teddy', 'Teddy', 'back', 'common'],
  ['back_balloon', 'Herzballon', 'back', 'rare'],
  ['pet_cat', 'Kätzchen', 'pet', 'common'],
  ['pet_shiba', 'Shiba', 'pet', 'rare'],
  ['pet_bunny', 'Häschen', 'pet', 'common'],
  ['pet_fox', 'Füchschen', 'pet', 'rare'],
  ['pet_redpanda', 'Roter Panda', 'pet', 'epic'],
  ['pet_panda', 'Pandabär', 'pet', 'rare'],
  ['pet_bear', 'Teddybär', 'pet', 'common'],
  ['pet_hamster', 'Hamster', 'pet', 'common'],
  ['pet_penguin', 'Pinguin', 'pet', 'rare'],
  ['pet_chick', 'Küken', 'pet', 'common'],
  ['pet_owl', 'Eule', 'pet', 'rare'],
  ['pet_frog', 'Fröschchen', 'pet', 'common'],
  ['pet_axolotl', 'Axolotl', 'pet', 'epic'],
  ['pet_turtle', 'Schildkröte', 'pet', 'rare'],
  ['pet_bee', 'Bienchen', 'pet', 'rare'],
  ['pet_bat', 'Fledermaus', 'pet', 'epic'],
  ['pet_slime', 'Schleimi', 'pet', 'common'],
  ['pet_ghost', 'Geistchen', 'pet', 'rare'],
  ['pet_jelly', 'Qualle', 'pet', 'epic'],
  ['pet_fish', 'Blubberfisch', 'pet', 'epic'],
  ['pet_mushroom', 'Pilzchen', 'pet', 'rare'],
  ['pet_brick', 'Stein-Freund', 'pet', 'epic'],
  ['pet_cloud', 'Wölkchen', 'pet', 'epic'],
  ['pet_robot', 'Robo', 'pet', 'epic'],
  ['pet_dragon', 'Mini-Drache', 'pet', 'legendary'],
  ['pet_unicorn', 'Einhorn', 'pet', 'legendary'],
  ['pet_wolf', 'Wolf', 'pet', 'rare'],
  ['pet_retriever', 'Golden Retriever', 'pet', 'rare'],
  ['pet_arcticfox', 'Polarfuchs', 'pet', 'rare'],
  ['pet_horse', 'Pferd', 'pet', 'epic'],
  ['pet_deer', 'Hirsch', 'pet', 'epic'],
  ['pet_tiger', 'Tiger', 'pet', 'epic'],
  ['pet_eagle', 'Adler', 'pet', 'epic'],
  ['pet_lion', 'Löwe', 'pet', 'legendary'],
  ['pet_drake', 'Drache', 'pet', 'legendary'],
  ['veh_skate', 'Skateboard', 'vehicle', 'rare'],
  ['veh_hover', 'Hoverboard', 'vehicle', 'legendary'],
  ['veh_kickscooter', 'Tretroller', 'vehicle', 'common'],
  ['veh_scooter', 'E-Scooter', 'vehicle', 'epic'],
  ['veh_bike', 'Fahrrad', 'vehicle', 'rare'],
  ['veh_moped', 'Motorroller', 'vehicle', 'epic'],
  ['veh_moto', 'Motorrad', 'vehicle', 'legendary'],
  ['veh_car', 'Sportwagen', 'vehicle', 'legendary'],
  ['veh_car_blue', 'Sportwagen Blau', 'vehicle', 'legendary'],
  ['veh_kart', 'Go-Kart', 'vehicle', 'epic'],
  ['veh_ufo', 'UFO', 'vehicle', 'legendary'],
  ['veh_cloud', 'Wolke', 'vehicle', 'epic'],
  ['wings_angel', 'Engelsflügel', 'wings', 'legendary'],
  ['wings_gold', 'Goldflügel', 'wings', 'legendary'],
  ['wings_phoenix', 'Phönixflügel', 'wings', 'legendary'],
  ['wings_fire', 'Feuerflügel', 'wings', 'epic'],
  ['wings_shadow', 'Schattenflügel', 'wings', 'epic'],
  ['wings_owl', 'Eulenflügel', 'wings', 'rare'],
  ['wings_rainbow', 'Regenbogenflügel', 'wings', 'epic'],
  ['wings_galaxy', 'Galaxieflügel', 'wings', 'legendary'],
  ['wings_crystal', 'Kristallflügel', 'wings', 'legendary'],
  ['wings_demon', 'Dämonenflügel', 'wings', 'epic'],
  ['wings_dragon', 'Drachenflügel', 'wings', 'legendary'],
  ['wings_neon', 'Neonflügel', 'wings', 'epic'],
  ['wings_bat', 'Fledermausflügel', 'wings', 'rare'],
  ['wings_butterfly', 'Schmetterling', 'wings', 'epic'],
  ['wings_fairy', 'Feenflügel', 'wings', 'epic'],
  ['wings_cyber', 'Cyberflügel', 'wings', 'legendary'],
  ['xm_back_scarf', 'Weihnachtsschal', 'back', 'rare'],
  ['xm_back_tree', 'Mini-Weihnachtsbaum', 'back', 'legendary'],
  ['xm_back_candycanes', 'Zuckerstangen', 'back', 'epic'],
  ['xm_back_gifts', 'Geschenke-Stapel', 'back', 'epic'],
  ['xm_aura_snow', 'Schneegestöber', 'aura', 'epic'],
  ['xm_aura_lights', 'Lichterketten-Spirale', 'aura', 'legendary'],
  ['xm_aura_aurora', 'Nordlicht-Band', 'aura', 'legendary'],
  ['xm_wings_ice', 'Eiskristall-Flügel', 'wings', 'legendary'],
  ['xm_wings_angel', 'Goldene Sternenflügel', 'wings', 'legendary'],
  ['xm_hat_antlers', 'Rentier-Geweih', 'hat', 'epic'],
  ['xm_hat_elf', 'Elfenmütze', 'hat', 'epic'],
  ['xm_hat_lightcrown', 'Lichterketten-Krone', 'hat', 'legendary'],
  ['xm_hat_tophat', 'Schneemann-Zylinder', 'hat', 'epic'],
  ['xm_hat_earmuffs', 'Lebkuchen-Ohrenschützer', 'hat', 'rare'],
  ['xm_face_rednose', 'Rentier-Nase', 'face', 'epic'],
  ['xm_cape_winterwald', 'Winterwald', 'cape', 'epic'],
  ['xm_cape_lebkuchenhaus', 'Lebkuchenhaus', 'cape', 'epic'],
  ['xm_cape_zuckerstange', 'Zuckerstange', 'cape', 'rare'],
  ['xm_cape_schlittenmond', 'Rentierschlitten am Mond', 'cape', 'legendary'],
  ['xm_cape_pullover', 'Weihnachtspullover', 'cape', 'rare'],
  ['xm_cape_nordlicht', 'Nordlicht-Weihnacht', 'cape', 'legendary'],
  ['xm_pet_snowman', 'Schneemann', 'pet', 'epic'],
  ['xm_pet_reindeer', 'Rentier', 'pet', 'legendary'],
  ['xm_pet_gingerbread', 'Lebkuchenmann', 'pet', 'epic'],
  ['xm_pet_giftmonster', 'Geschenk-Monster', 'pet', 'legendary'],
  ['xm_pet_penguin', 'Pinguin mit Mütze', 'pet', 'epic'],
  ['xm_veh_sleigh', 'Weihnachtsschlitten', 'vehicle', 'legendary'],
];
